### ISSUE TITLE
Fuzzy search on display popup

### ISSUE THREAD

**Issue by SupremeTechnopriest** [camgraff/telescope-tmux.nvim#10]
Hello!  Thanks for the extension!. I was wondering if there is a way to make fuzzy search work with the tmux display popup.  When I try to type into the filter I get `Cannot make changes . 'Modifiable' is off`

Here is what I have tried so far:

`bind w display-popup -E -w 80% -h 80% nvim -c ":set modifiable|:Telescope tmux windows quit_on_select=true"`

```
bind s display-popup -E -w 80% -h 80% nvim -c ':lua \
  vim.opt.modifiable=true \
  require("telescope").extensions.tmux.sessions({ \
    quit_on_select=true \
  }) \
 '
```

Thanks!

**Comment by camgraff** [comment]
Hmm I haven't seen this before, is there something in your vimrc that could be setting `modifiable`? Maybe another plugin? You could try to reproduce with a minimal vimrc using just telescope and this extension.

**Comment by trevarj** [comment]
@SupremeTechnopriest most likely because of your dashboard plugin which starts unmodifiable

related: https://github.com/nvimdev/dashboard-nvim/issues/398

**Comment by SupremeTechnopriest** [comment]
Im willing to bet you are right.  Ill give it a try.  Feel free to close this. I almost never use dashboard so ill probably just remove it.

**Comment by SupremeTechnopriest** [comment]
Yup that was the issue!  Thank you!

**Comment by trevarj** [comment]
@SupremeTechnopriest if you want to re-enable, I figured out that you can just do
```
bind w display-popup -E -w 80% -h 80% nvim -c ":set modifiable|:Telescope tmux windows quit_on_select=true" tmp.txt
```
and it will bypass the dashboard by opening an empty `tmp.txt` file. You can name that whatever you want.

**Comment by SupremeTechnopriest** [comment]
Awesome, thank you!  Maybe ill reinstall it.
