### ISSUE TITLE
Quit on select seems to no longer work in tmux

### ISSUE THREAD

**Issue by pBorak** [camgraff/telescope-tmux.nvim#3]
It seems to me that the most recent  [PR](https://github.com/nvim-telescope/telescope.nvim/commit/6daf35c88c07dd4b220468968a742cda04889cd3) in telescope might have broken the tmux [command](https://github.com/camgraff/telescope-tmux.nvim#use-with-tmux-display-popup)

https://user-images.githubusercontent.com/45797239/143095434-68ebb37d-7a75-406f-8eda-0601dd61ea6f.mov

**Comment by camgraff** [comment]
I've opened an issue in telescope for this https://github.com/nvim-telescope/telescope.nvim/issues/1485

**Comment by camgraff** [comment]
They [reverted the commit](https://github.com/nvim-telescope/telescope.nvim/pull/1486). Looks like it broke some other things as well.

**Comment by pBorak** [comment]
Thanks for handling it and foremost, for creating such a lovely plugin.
